In [4]:
import pandas as pd

regression_df = pd.read_csv('data/regression.csv')

regression_df.head()

,latitude,longitude,accommodates,beds,bathrooms,half_bathrooms,shared_bathrooms,room_type_Entire_home/apt,room_type_Hotel_room,room_type_Private_room,room_type_Shared_room,price
0,-22.96599,-43.17940,5,2.0,1,0,0,1,0,0,0,1357.0
1,-22.97735,-43.19105,3,1.0,1,0,0,1,0,0,0,865.0
2,-22.98107,-43.19136,2,1.0,1,1,0,1,0,0,0,373.0
3,-22.96825,-43.18237,4,1.0,1,0,0,1,0,0,0,366.0
4,-22.97696,-43.18933,5,3.0,2,0,0,1,0,0,0,368.0

In [5]:
from sklearn.model_selection import train_test_split, KFold

X = regression_df.loc[:, regression_df.columns != 'price']
X = (X - X.mean())/X.std() #Normalizing

y = regression_df.loc[:, 'price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import r2_score

model = MLPRegressor()

regressor = model().fit(X_train.values, y_train.values)

y_predicted = regressor.predict(X_test)

r2_score(y_test, y_predicted)